version: "3"

services:
  Twitter:
    image: drakkarsoftware/Twitter:stable
    volumes:
       - ./logs:/Twitter/logs
       - ./backtesting:/Twitter/backtesting
       - ./tentacles:/Twitter/tentacles
       - ./user:/Twitter/user
    ports:
       - ${PORT:-80}:${PORT:-5001}
    restart: always
  
  watchtower:
    image: containrrr/watchtower
    restart: always
    command: --cleanup --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
